<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:
Takes in the correct shape data and send it to the next layer
### Hidden Layer:
Can be one or many. Receives the data from the previous layer, transforms it using the weights and activation function, and sends it to the next layer.
### Output Layer:
Takes the data from the previous layer and transforms it into the right shape. Also uses an activation function to put it into the right format (sigmoid for 0-1, etc.).
### Neuron:
An individual piece of a layer that takes in data, transforms it according to weights and activation function, then sends it to the next layer.
### Weight:
Initialized at random, applied to data, then refined to estimate relationships between inputs and outputs.
### Activation Function:
For classification problems the activation function puts the data into the expected format (sigmoid for 0-1, etc.) and can also activate or turn off neurons for a relu.
### Perceptron:
The simplest type of neural network.


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [2]:
import pandas as pd
import numpy as np
np.random.seed(42)
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
#          'bias': [1,1,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')
df.head()

x1  x2  y
0   0   0  1
1   1   0  1
2   0   1  1
3   1   1  0

In [3]:
inputs = np.array([df.x1,df.x2,])
inputs = inputs.T
correct_outputs = np.array([df.y]).T
print(inputs)
print(correct_outputs)

[[0 0]
 [1 0]
 [0 1]
 [1 1]]
[[1]
 [1]
 [1]
 [0]]


In [4]:
# Initialize random weights
weights = 2 * np.random.random((2,1)) -1
weights

array([[-0.25091976],
       [ 0.90142861]])

In [5]:
# Calculate weighted sum of inputs and weights
weighted_sum = np.dot(inputs, weights)
weighted_sum

array([[ 0.        ],
       [-0.25091976],
       [ 0.90142861],
       [ 0.65050885]])

In [6]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

In [7]:
# Output the activated value for the end of 1 training epoch
activated_output = sigmoid(weighted_sum)
activated_output

array([[0.5       ],
       [0.43759713],
       [0.71124299],
       [0.65712512]])

In [8]:
# Take difference of output and true values to calculate error
error = correct_outputs - activated_output
error

array([[ 0.5       ],
       [ 0.56240287],
       [ 0.28875701],
       [-0.65712512]])

In [9]:
# Gradient descent
adjustments = error * sigmoid_derivative(weighted_sum)
adjustments

array([[ 0.125     ],
       [ 0.13841065],
       [ 0.05930387],
       [-0.14805798]])

In [10]:
weights += np.dot(inputs.T, adjustments)
weights

array([[-0.26056708],
       [ 0.81267451]])

In [13]:
from sklearn.metrics import accuracy_score
# Try it all together
inputs = np.array([df.x1,df.x2])
inputs = inputs.T
correct_outputs = np.array([df.y]).T
weights = 2 * np.random.random((2,1)) - 1
bias = 7


for iteration in range(10000):
    
    weighted_sum = np.dot(inputs, weights) + bias
    activated_output = sigmoid(weighted_sum)
    error = correct_outputs - activated_output
    adjustments = error * sigmoid_derivative(weighted_sum)
    weights += np.dot(inputs.T, adjustments)
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)

predictions = [1 if pred >= .5 else 0 for pred in activated_output]
print("Predictions")
print(predictions)

print("Accuracy")
print(accuracy_score(correct_outputs, predictions))

Weights after training
[[-4.66666667]
 [-4.66666667]]
Output after training
[[0.99908895]
 [0.91160032]
 [0.91160032]
 [0.08839968]]
Predictions
[1, 1, 1, 0]
Accuracy
1.0


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [59]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [60]:
diabetes.shape

(768, 9)

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [61]:
from sklearn.preprocessing import Normalizer

features = list(diabetes)[:-1]

X = diabetes[features].copy()

normalizer = Normalizer()
X = normalizer.fit_transform(X)
X

array([[0.03355237, 0.82762513, 0.40262844, ..., 0.18789327, 0.00350622,
        0.27960308],
       [0.008424  , 0.71604034, 0.55598426, ..., 0.22407851, 0.00295683,
        0.26114412],
       [0.04039768, 0.92409698, 0.32318146, ..., 0.11765825, 0.00339341,
        0.16159073],
       ...,
       [0.02691539, 0.65135243, 0.38758161, ..., 0.14103664, 0.00131885,
        0.16149234],
       [0.00665306, 0.83828547, 0.39918356, ..., 0.20025708, 0.00232192,
        0.31269379],
       [0.00791454, 0.73605211, 0.55401772, ..., 0.24060198, 0.00249308,
        0.18203439]])

In [62]:
X.shape

(768, 8)

In [84]:
X = X.copy().T
t = np.full((1,len(X[0])),1)
X = np.concatenate((X,t))
X = X.T
X.shape

(768, 9)

In [85]:
X[0:5]

array([[0.03355237, 0.82762513, 0.40262844, 0.19572216, 0.        ,
        0.18789327, 0.00350622, 0.27960308, 1.        ],
       [0.008424  , 0.71604034, 0.55598426, 0.24429612, 0.        ,
        0.22407851, 0.00295683, 0.26114412, 1.        ],
       [0.04039768, 0.92409698, 0.32318146, 0.        , 0.        ,
        0.11765825, 0.00339341, 0.16159073, 1.        ],
       [0.00661199, 0.58846737, 0.43639153, 0.15207584, 0.62152733,
        0.185797  , 0.0011042 , 0.13885185, 1.        ],
       [0.        , 0.5963863 , 0.17412739, 0.15236146, 0.73133502,
        0.18762226, 0.00996009, 0.14365509, 1.        ]])

In [86]:
target = list(diabetes)[-1]
y = np.array([diabetes[target]]).T
y.shape

(768, 1)

In [92]:
##### Update this Class #####

class Perceptron:
    
    def __init__(self, niter = 10000):
        self.niter = niter
        self.manual_bias = 0
        self.errors = []
    
    def __sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def __sigmoid_derivative(self, x):
        sx = self.__sigmoid(x)
        return sx * (1-sx)

    def fit(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """
       
        # Randomly Initialize Weights
        self.weights = 2 * np.random.random((X.shape[1],1)) - 1
#         print("weights: ",self.weights)

#         Let's check the errors

        for i in range(self.niter):
            
            # Weighted sum of inputs / weights
            weighted_sum = np.dot(X, self.weights) + self.manual_bias
            
#             print("weighted sums shape: ",weighted_sum.shape)

            # Activate!
            self.activated_output = self.__sigmoid(weighted_sum)
#             print("activated output shape: ",self.activated_output.shape)

            # Cac error
            error = y - self.activated_output
            self.errors.append(error)
            
            # Update the Weights
            adjustments = error * self.__sigmoid_derivative(weighted_sum)
            self.weights += np.dot(X.T, adjustments)
            
        return self
    
    def fit_predict(self, X, y):
        self.fit(X, y)
        return self.predict(X)

    def predict(self, X):
        """Return class label after unit step"""
        predictions = [1 if pred >= .5 else 0 for pred in self.activated_output]
        return predictions

In [93]:
pn = Perceptron()
y_pred = pn.fit(X, y)
y_pred = pn.predict(X)

In [94]:
print(y_pred[:5])
set(y_pred)

[0, 0, 0, 0, 0]


{0}

In [95]:
len(pn.weights)

9

In [96]:
print(pn.errors[0][:5])
print(pn.errors[-1][:5])

[[ 0.6150774 ]
 [-0.36146695]
 [ 0.53929713]
 [-0.2938923 ]
 [ 0.71617518]]
[[ 1.00000000e+00]
 [-6.91581408e-11]
 [ 9.99999998e-01]
 [-4.18048068e-10]
 [ 9.99999994e-01]]


In [97]:
pn.errors[0][:5] > pn.errors[-1][:5]
# Errors are getting larger?
# I must be making the adjustments incorrectly?

array([[False],
       [False],
       [False],
       [False],
       [False]])

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?